### ISSUE TITLE
Blank page 

### ISSUE THREAD

**Issue by Ademola101** [pranay202/prohub#19]
All I have i blank page when I click the demo link on mobile ![Screenshot_20220630-163718.png](https://user-images.githubusercontent.com/54910756/176718687-4fded052-2842-47d0-9421-eda886ce3640.png)

**Comment by dublinsubway** [comment]
Same with PC. Either the host is expired or something is wrong with the demo generally, but it's not working, unfortunately.

**Comment by pranay202** [comment]
Heroku sucks!! It automatically goes down after some days! Have to deploy it on vercel!

Contributions are welcome, interested ones can proceed further.
